export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      image: '../public/images/product1.svg',
      title: 'Smart camera',
      description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
      price: "NGN 200,000",
      addToCartLink: '/cart/add/1', 
    },
    {
        id: 2,
        image: '../public/images/product2.svg',
        title: 'Smart vinvit camera',
        description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
        price: "NGN 100,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 3,
        image: '../public/images/product3.svg',
        title: 'Infra-red Bullet camera',
        description: 'A versatile security camera device that helps to monitor your home effortlessly',
        price: "NGN 200,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 4,
        image: '../public/images/product4.svg',
        title: 'Pan-tilt zoom camera',
        description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
        price: "NGN 150,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id:5,
        image: '../public/images/product5.svg',
        title: 'Smart camera',
        description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
        price: "NGN 200,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 6,
        image: '../public/images/product6.svg',
        title: 'Motorized varifocal',
        description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
        price: "NGN 200,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 7,
        image: '../public/images/product7.svg',
        title: 'Remotable camera',
        description: 'A remotable camera device that allows and helps to control and monitor your home effortlessly',
        price: "NGN 100,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 8,
        image: '../public/images/product8.svg',
        title: 'Smart camera',
        description: 'Outdoor camera housing device that help to monitor your home effortlessly',
        price: "NGN 300,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 9,
        image: '../public/images/product9.svg',
        title: 'Smart camera',
        description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
        price: "NGN 200,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 10,
        image: '../public/images/product10.svg',
        title: 'Smart vinvit camera',
        description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
        price: "NGN 100,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 11,
        image: '../public/images/product11.svg',
        title: 'Infra-red Bullet camera',
        description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
        price: "NGN 200,000",
        addToCartLink: '/cart/add/1', 
      },
      {
        id: 12,
        image: '../public/images/product12.svg',
        title: 'Pan-tilt zoom camera',
        description: 'A versatile voice-activated device that helps to monitor your home effortlessly',
        price: "NGN 150,000",
        addToCartLink: '/cart/add/1', 
      },
    ]);
  }
  